import image from '/src/assets/Backgrounds/About-Team-User.png';
import image2 from '/src/assets/Backgrounds/About-Team-User2.png';
import image3 from '/src/assets/Backgrounds/About-team-User3.png';

const DataTeam = [
    {id: 1,
      user: 'Aaron mendoza',
      range: 'Presidente',
      image: image,
      section: 'Administracion',
    },
    {id: 2,
      user: 'Aaron mendoza',
      range: 'Presidente',
      image: image2,
      section: 'Administracion',
    },
    {id: 3,
      user: 'Aaron mendoza',
      range: 'Presidente',
      image: image3,
      section: 'Administracion',
    },
    {id: 4,
      user: 'Aaron mendoza',
      range: 'Presidente',
      image: image,
      section: 'Administracion',
    },
    {id: 5,
      user: 'Aaron mendoza',
      range: 'Logística',
      image: image2,
      section: 'Operaciones',
    },
    {id: 6,
      user: 'Aaron mendoza',
      range: 'Logística',
      image: image,
      section: 'Operaciones',
    },
    {id: 7,
      user: 'Aaron mendoza',
      range: 'Logística',
      image: image2,
      section: 'Operaciones',
    },
    {id: 8,
      user: 'Aaron mendoza',
      range: 'Logística',
      image: image3,
      section: 'Operaciones',
    },
  ]
  
  export default DataTeam;
  